import { Provider } from "./provide";
import "../../tailwind.config";
import "../styles/global.css";

export const metadata = {
  title: "pick",
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  session: never;
}) {
  return (
    <html lang="ko">
      <body className="">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
