import { Provider } from "./provide";
import Head from "next/head";
import "../../tailwind.config";
import "../styles/global.css";

export const metadata = {
  title: "pick",
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  session: never;
}) {
  return (
    <html lang="ko">
      <Head>
        <link rel="icon" href={metadata.icons.icon} />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className="">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
