export const metadata = {
  title: "pick",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className=" m-0">{children}</body>
    </html>
  );
}
